project_id = "wakgxinhspihyktlasni"

[functions.analyze-sources]
verify_jwt = false

[functions.generate-article]
verify_jwt = false
 
 [functions.seo-audit]
 verify_jwt = false

[functions.keyword-research]
verify_jwt = false
