project_id = "wakgxinhspihyktlasni"

[functions.analyze-sources]
verify_jwt = false

[functions.generate-article]
verify_jwt = false
 
 [functions.seo-audit]
 verify_jwt = false

[functions.keyword-research]
verify_jwt = false

[functions.publish-to-wp]
enabled = true
verify_jwt = true
import_map = "./functions/publish-to-wp/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/publish-to-wp/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/publish-to-wp/*.html" ]
